version: "3.8"
name: sqlx-issue-dev 
services:
  postgres:
    image: postgres:16
    restart: always
    command: -p 21101
    environment:
      POSTGRES_PASSWORD: dev_password
      POSTGRES_USER: dev
      POSTGRES_DB: dev
    expose:
      - "21101"
    ports:
      - "21101:21101"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
